# Configuration for Alacritty, the GPU enhanced terminal emulator.

live_config_reload: true

window:
  dimensions:
    columns: 95
    lines: 28
    x: 450
    y: 100
  padding:
    x: 2
    y: 2
  dynamic_title: true

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

draw_bold_text_with_bright_colors: true
# Font configuration
font:
  normal:
    family: Fira Mono Nerd Font
  size: 14.5

cursor:
  style:
    shape: block
    blinking: on

key_bindings:
  - { key: F11, action: ToggleFullscreen }
colors:
  # Default colors
  primary:
    background: '#161616'
    foreground: '#ffffff'

  # Normal colors
  normal:
    black: '#0c0c0c'
    red: '#c50f1f'
    green: '#13a10e'
    yellow: '#c19c00'
    blue: '#0037da'
    magenta: '#881798'
    cyan: '#3a96dd'
    white: '#cccccc'

  # Bright colors
  bright:
    black: '#767676'
    red: '#e74856'
    green: '#16c60c'
    yellow: '#f9f1a5'
    blue: '#3b78ff'
    magenta: '#b4009e'
    cyan: '#61d6d6'
    white: '#f2f2f2'
theme: custom_dark
