[[targets]]
name = "kitty"
light = "PaperColor Light"
dark = "Arthur"
[[targets]]
name = "bat"
light = "Monokai Extended Light"
dark = "Monokai Extended"

[[targets]]
name = "alacritty"
light = "Default.light"
dark = "Default.dark"

