[[targets]]
name = "kitty"
light = "Alabaster"
dark = "Mathias"

[[targets]]
name = "bat"
light = "Monokai Extended Light"
dark = "Monokai Extended"

[[targets]]
name = "alacritty"
light = "Alabaster"
dark = "Campbell"

