add_newline = false
format = """
$directory\
$git_branch\
$line_break\
$status\
$container\
$character\
"""

[line_break]
disabled = true

[directory]
truncation_length = 1

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[container]
symbol = '*'
format = '[$symbol](green)'
