add_newline = false
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$line_break\
$status\
$container\
$character\
"""

[line_break]
disabled = true

[sudo]
disabled = false

[directory]
truncation_length = 1

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
