add_newline = false
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$sudo\
$cmd_duration\
$line_break\
$status\
$container\
$character\
"""

[line_break]
disabled = true

[sudo]
disabled = false


